### ISSUE TITLE
Schauen wie man Eduvidual Logindaten ins Plugin holt

### ISSUE THREAD

**Issue by Tobi696** [htl-grieskirchen-core/plugin-eduvidual-news#12]
Einfoch in da HttpGet-Get News methode moi username + passwort von am user Console.WriteLinen

**Comment by Tobi696** [comment]
30min

**Comment by EinboeckFranz** [comment]
ma konn se hoid mit de Microsoft Login Daten ned einfoch üba den /login/token.php eiloggn, do miassatn wa schaun wie de des bei eduvidual genau gmocht hobn

**Comment by Tobi696** [comment]
Token reicht jetzt eh
