### ISSUE TITLE
plugin-eduvidual-news moodle API analysieren: alle Items eines Users möglichst effizient bekommen (# API Calls)

### ISSUE THREAD

**Issue by Tobi696** [htl-grieskirchen-core/plugin-eduvidual-news#6]
**+ Timestamp updated at, created at, deleted at?**
30min

**Comment by EinboeckFranz** [comment]
Schaut so aus ois würde ma pro Course de Methode ```core_course_get_course_content_items``` ausführn miassn

**Comment by Tobi696** [comment]
@EinboeckFranz i griag koa token mid dem i access auf de `core_course_get_course_content_items` hätt 😬

**Comment by EinboeckFranz** [comment]
klumpat

**Comment by Tobi696** [comment]
Fazit: wir parsen HTML
